### ISSUE TITLE
A user can't be updated to grant them access to a portal

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo-portal-issues#10]
When a new portal is added, the `Update User` button is deactivated

Gloo Portal version: 0.4.14

**Comment by djannot** [comment]
![portal-add-portal-to-user](https://user-images.githubusercontent.com/3184742/100539231-54112f80-3235-11eb-9550-e7e34af875e2.png)

**Comment by arianaw66** [comment]
Not able to reproduce- looks like this has already been fixed
