### ISSUE TITLE
adding or removing a Portal access right to a Group empties the group members list

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo-portal-issues#105]
Using the admin UI, when I add or remove a Portal Access to a Group (using the modal below) will completely delete the members of that Group

![image](https://user-images.githubusercontent.com/9626829/130471146-6cf9c4c2-42a4-484f-8551-c4bc91a18abf.png)

**Comment by marcogschmidt** [comment]
@bcollard On which version did you observe this behavior?

**Comment by marcogschmidt** [comment]
Should have been fixed as part of https://github.com/solo-io/dev-portal/issues/1740, we will look into this.

**Comment by bcollard** [comment]
I think this was v1.1.0-beta6
