### ISSUE TITLE
blacklist OpenAPI operations of an APIDoc

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo-portal-issues#109]
Given an APIProduct referencing the operations of an APIDoc,
I want to be able to select a subset of them, using a blacklist approach: there are certain operationId that I don't want to expose.

See also: https://github.com/solo-io/gloo-portal-issues/issues/108

**Comment by chrisgaun** [comment]
Will be solved with https://github.com/solo-io/gloo-portal-issues/issues/108

**Comment by marcogschmidt** [comment]
This feature has been implemented and will be released today with Gloo Portal `1.1.0`.
