### ISSUE TITLE
Can't update Portal images

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo-portal-issues#11]
After a Portal is created, the images can't be updated.

Gloo Portal version: 0.4.14

**Comment by djannot** [comment]
![portal-images](https://user-images.githubusercontent.com/3184742/100539270-afdbb880-3235-11eb-85f7-0bae1b6e295e.png)

**Comment by marcogschmidt** [comment]
This has been implemented and will be released in `v0.5.2`.
