### ISSUE TITLE
The use of a VHO cause errors in Gloo Portal

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo-portal-issues#112]
**Describe the bug**
Given a VS created in Gloo Edge and using a reference to a VHO (VirtualHostOption) CR,
Gloo Portal will report errors like this:
```
W0831 10:04:09.697396       1 reflector.go:436] pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/reflector.go:167: watch of *v1.VirtualService ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode watch event: v1.VirtualService.Status: Spec: unmarshalerDecoder: unknown field \"optionsConfigRefs\" in gateway.solo.io.VirtualHost, error found in #10 byte of ...|em\"}}}}]}},\"status\":|..., bigger context ...|ult-httpbin-8000\",\"namespace\":\"gloo-system\"}}}}]}},\"status\":{\"reportedBy\":\"gateway\",\"state\":1,\"subre|...") has prevented the request from succeeding
E0831 10:04:10.525506       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/reflector.go:167: Failed to watch *v1.VirtualService: failed to list *v1.VirtualService: v1.VirtualServiceList.Items: []v1.VirtualService: v1.VirtualService.Status: Spec: unmarshalerDecoder: unknown field "optionsConfigRefs" in gateway.solo.io.VirtualHost, error found in #10 byte of ...|em"}}}}]}},"status":|..., bigger context ...|ult-httpbin-8000","namespace":"gloo-system"}}}}]}},"status":{"reportedBy":"gateway","state":1,"subre|...
```

**To Reproduce**
See https://gist.github.com/bcollard/45f2c8ff0fa9ca7b4d9b890bf1219bb9

**Expected behavior**
No errors

**Additional context**
- Tested with Gloo Portal version 1.0.2 and 1.1.0-beta6
- Gloo Edge v1.8.5

**Comment by jehawley** [comment]
This might be fixed by upgrading our solo-apis version.

**Comment by marcogschmidt** [comment]
This feature has been implemented and will be released today with Gloo Portal `1.1.0`.

**Comment by niphaphorndream31-sudo** [comment]
> **Describe the bug** Given a VS created in Gloo Edge and using a reference to a VHO (VirtualHostOption) CR, Gloo Portal will report errors like this:
> 
> ```
> W0831 10:04:09.697396       1 reflector.go:436] pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/reflector.go:167: watch of *v1.VirtualService ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode watch event: v1.VirtualService.Status: Spec: unmarshalerDecoder: unknown field \"optionsConfigRefs\" in gateway.solo.io.VirtualHost, error found in #10 byte of ...|em\"}}}}]}},\"status\":|..., bigger context ...|ult-httpbin-8000\",\"namespace\":\"gloo-system\"}}}}]}},\"status\":{\"reportedBy\":\"gateway\",\"state\":1,\"subre|...") has prevented the request from succeeding
> E0831 10:04:10.525506       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/reflector.go:167: Failed to watch *v1.VirtualService: failed to list *v1.VirtualService: v1.VirtualServiceList.Items: []v1.VirtualService: v1.VirtualService.Status: Spec: unmarshalerDecoder: unknown field "optionsConfigRefs" in gateway.solo.io.VirtualHost, error found in #10 byte of ...|em"}}}}]}},"status":|..., bigger context ...|ult-httpbin-8000","namespace":"gloo-system"}}}}]}},"status":{"reportedBy":"gateway","state":1,"subre|...
> ```
> 
> **To Reproduce** See https://gist.github.com/bcollard/45f2c8ff0fa9ca7b4d9b890bf1219bb9
> 
> **Expected behavior** No errors
> 
> **Additional context**
> 
> * Tested with Gloo Portal version 1.0.2 and 1.1.0-beta6
> * Gloo Edge v1.8.5

**Comment by hyawhein734-gif** [comment]
MrRop14
