### ISSUE TITLE
Portal CRDs fail to sync in ArgoCD deployment

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo-portal-issues#116]
**Describe the bug**
When deploying Portal 1.1 in an ArgoCD app-of-apps pattern, the Portal CRDs (e.g., apidocs, apiproducts) consistently fail to sync, leaving the Portal ArgoCD app in an out-of-sync state.

**To Reproduce**
1. Follow setup directions for ArgoCD, Gloo Edge, and Gloo Portal, using the readme in Solo [gitops-library](https://github.com/solo-io/gitops-library). Observe that `gloo-portal-helm` app is OutOfSync, as shown in snapshots below. Drill down and observe that specifically it’s failing to add an empty `properties` object inside `openAPIV3Schema` stanza on all the Portal CRDs, and Argo just continues retrying. See snaps below.

<img width="1435" alt="Screen Shot 2021-09-28 at 7 09 02 AM" src="https://user-images.githubusercontent.com/52334260/135077016-608a6d97-0582-49ad-a6e0-b1c88f270a3b.png">

<img width="1131" alt="Screen Shot 2021-09-28 at 7 14 13 AM" src="https://user-images.githubusercontent.com/52334260/135077084-51b4f9ff-2a00-4bac-8913-eaa842d3a7a0.png">

<img width="1154" alt="Screen Shot 2021-09-27 at 5 42 10 PM" src="https://user-images.githubusercontent.com/52334260/135077124-cff667ba-8907-48b7-851b-cbae30740cd7.png">

**Expected behavior**
The `gloo-portal-helm` app syncs successfully.

**Additional context**
The GKE cluster is gke_solo-test-236622_us-east1-d_jimb-portal-cbp.
- Gloo Portal version 1.1.0
- Kubernetes version v1.20.9-gke.1001
- Gateway technology and version (e.g. Gloo Edge Enterprise 1.9.0-beta14)

**Comment by marcogschmidt** [comment]
The fix for this issue has been release in `v1.2.0-beta1`.
