### ISSUE TITLE
Using Portal 1.1 with Edge 1.9 causes failures with ArgoCD deployments

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo-portal-issues#117]
**Describe the bug**
Using Portal 1.1 with Edge 1.9 causes failures with ArgoCD deployments. 

@marcogschmidt believes this is related to a recent solo-kit change where we allow multiple controllers to set their dedicated status on a resource. Gloo Portal is still pinned to an older version of the Gloo Edge APIs, so it gets confused by the new `statuses` field.

```
E0929 12:40:34.051168       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/reflector.go:167: Failed to watch *v1.VirtualService: failed to list *v1.VirtualService: v1.VirtualServiceList.ListMeta: v1.ListMeta.TypeMeta: Kind: Items: []v1.VirtualService: v1.VirtualService.Status: unmarshalerDecoder: unknown field "statuses" in gateway.solo.io.VirtualServiceStatus, error found in #10 byte of ...|te":1}}}}}}],"kind":|..., bigger context ...|gateway-proxy":{"reportedBy":"gloo","state":1}}}}}}],"kind":"VirtualServiceList","metadata":{"contin|...
```

**To Reproduce**
1. Follow setup directions for ArgoCD, Gloo Edge, and Gloo Portal, using the readme in Solo gitops-library. 
2. Deploy petstore `Application` via ArgoCD.
3. See error described above.

**Expected behavior**
ArgoCD should be able to deploy Gloo artifacts without error using Portal 1.1 and Edge 1.9.

**Additional context**
- Gloo Portal version 1.1.0
- Gateway technology and version (Gloo Edge Enterprise 1.9.0-beta14)

**Comment by marcogschmidt** [comment]
The fix has been released with the following Gloo Portal versions:
- v1.2.0-beta1
- v1.1.1
- v1.0.5
