### ISSUE TITLE
Can't remove an API Product from a Portal

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo-portal-issues#12]
When clicking on the delete button and then confirming the action by clicking on the `Remove this API` button, nothing happens.

Gloo Portal version: 0.4.14

**Comment by djannot** [comment]
![portal-remove-api-product](https://user-images.githubusercontent.com/3184742/100539407-8ec79780-3236-11eb-8daa-74d6d3dc2dc3.png)

**Comment by arianaw66** [comment]
I don't believe this delete button is present anymore.
If we need this functionality, we can just use this issue to track that instead.

**Comment by marcogschmidt** [comment]
I think we can close this. Adding/removing API product from a Portal can now be done by selecting/deselecting entries in this modal:
![image](https://user-images.githubusercontent.com/16148461/104038284-f44a6480-51a2-11eb-899b-0e9ebde5307a.png)
