### ISSUE TITLE
Dead Portal-Edge cross-product links in Portal reference docs

### ISSUE THREAD

**Issue by antonioberben** [solo-io/gloo-portal-issues#127]
Hi team, there are some dead links in our docs.

For example:
https://docs.solo.io/gloo-portal/latest/reference/api/route/#gloo.solo.io.RouteOptions

![image](https://user-images.githubusercontent.com/5262332/138120173-6d8feff1-9282-45cd-b09c-3c498c6388d2.png)

As we have briefly discussed, those links are autogenerated. So that be aware that this issue might occur in many other places.

Thank you!

**Comment by jameshbarton** [comment]
These dead links occur everywhere in the Portal reference docs that we refer to native Edge components, like `gloo.solo.io.RouteOptions` in the example above. These autogen links need to be able to reference these components across the doc sets, or we need to reproduce selected native Edge components like this in the Portal reference docs.

**Comment by Rachael-Graham** [comment]
fixed in https://github.com/solo-io/dev-portal/pull/2498
