### ISSUE TITLE
Calling ListAPIProducts takes longer than expected

### ISSUE THREAD

**Issue by antonioberben** [solo-io/gloo-portal-issues#128]
portal version 1.1.1
gloo edge version 1.9.0

When the front-end calls `ListAPIProducts` method the response time is lower each time.

First time takes around 30 seconds. After 6 times, it takes less than 3 ms.

Having the first call taking more than 30 seconds, it is too much.

Here some screenshots of the logs

![image (2)](https://user-images.githubusercontent.com/5262332/138672926-0eb157db-7177-4b50-b172-7eff53dd19a7.png)
![image (3)](https://user-images.githubusercontent.com/5262332/138672957-e9150d3c-c7e2-4467-886e-3cb90a40466e.png)

To help on reproducing the scenario:

The APIDocs containing the swagger specs are stored in configmaps
The APIProducts are 10. Each of them pointing to 1 APIDoc.
The number of operations in the swagger specs are, for those 10 products, as follows:
9, 10, 5, 14, 10, 35, 35, 16, 2, 10
Making a total of 146 operations which are added to the status of the resources.

The pods (proxy and portal controller) were deployed in the same kubernetes node.

Thank you

To get an example of the heavy swagger spec used for this scenario, please, contact @antonioberben

**Comment by arianaw66** [comment]
Resolved and released in v1.2.0-beta4
