### ISSUE TITLE
Timeout option for the autogenerated VirtualServices

### ISSUE THREAD

**Issue by antonioberben** [solo-io/gloo-portal-issues#130]
portal version 1.1.1
gloo edge version 1.9.0

So far, once you create portals, the VirtualServices are autogenerated.

This, block us to, for example, configure a timeout for the VirtualService as it is possible in Gloo Edge: 
https://docs.solo.io/gloo-edge/latest/guides/traffic_management/request_processing/timeout/

This is related to https://github.com/solo-io/gloo-portal-issues/issues/128 and https://github.com/solo-io/gloo-portal-issues/issues/131

Here an example of the accesslogs which shows an UT response flag (Upstream Timeout)

```
gateway-proxy-5f6d4cf74b-7whft gateway-proxy {"upstreamCluster":"gloo-portal.gloo-portal_gloo-portal","bytesReceived":5,"method":"POST","path":"/app.portal.gloo.solo.io.WebAppApi/ListAPIProducts","correlationId":null,"startTime":"","protocol":"HTTP/2","duration":15001,"userAgent":"Chrome/91.0.4472.114 Safari/537.36","bytesSent":0,"responseCode":504,"upstreamHost":"x.x.x.x:8080","responseFlag":"UT","upstreamServiceDuration":null}
```

Notice the duration of 15 seconds which is the value by default.

Thank you

**Comment by arianaw66** [comment]
Should be released in v1.2.0-beta3
