### ISSUE TITLE
expose Gloo Edge clusterHeader in RoutingDestination

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo-portal-issues#134]
**Is your feature request related to a problem? Please describe.**
Implementing Gloo Edge dynamic routing from Gloo Portal. 

In Gloo Edge, you can manually build the upstream cluster name and then use a special header, called `clusterHeader` to force the routing to a given upstream cluster.
This requires a transformation. 

In Gloo Portal, you can add transformations in the Route options.
But you cannot leverage the `clusterHeader` in the routing destination: https://docs.solo.io/gloo-portal/latest/reference/api/route/#routingdestination

The goal of this issue is to expose the `clusterHeader` as a valid RoutingDestination in Gloo Portal

**Comment by marcogschmidt** [comment]
This has been released with Gloo Portal `1.2.0-beta5`.
