### ISSUE TITLE
Allow Environments with identical domains when route generation disabled

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo-portal-issues#140]
**Is your feature request related to a problem? Please describe.**
A user with a multi-tenant portal would like to have `Environments` with identical domains and distinguished by their base paths. That is impossible today. However, this could be supported when `Environment` route generation is disabled, which fits the customer's use case.

**Describe the solution you'd like**
Allow Environments to have identical domains when route generation is disabled.

**Additional context**
Internal conversation: https://solo-io.slack.com/archives/G01DET26YP7/p1638995805141500

**Comment by marcogschmidt** [comment]
This has been released with Gloo Portal `1.2.0-beta5`.
