### ISSUE TITLE
Expand options for variable expansions in Environment basePath

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo-portal-issues#141]
**Is your feature request related to a problem? Please describe.**
Multi-tenant users are frustrated when it is difficult to disambiguate different APIProducts owned by separate teams when they are targeted at a single Environment. The basePath in the [EnvironmentSpec](https://docs.solo.io/gloo-portal/latest/reference/api/environment/#environmentspec) supports only a variable `{%version%}` to help with this. 

We need to provide other variable options as well. Some suggestions:
* APIProduct name
* APIProduct namespace
* Label-based options

**Describe the solution you'd like**
Multi-tenant users can easily develop conventions that allow different product owners to avoid naming conflicts for APIProducts within a single environment. Possible examples:
* `/api/{%product-name%}/{%version%}`
* `/{%product-namespace%}/{%product-name%}/{%version%}`
* `/api/{%Label:my-product-name}/{%version%}`

**Describe alternatives you've considered**
Establish a convention to put other distinguishing bits like product name into the current `{%version%}` variable.

**Comment by jameshbarton** [comment]
We decided after a discussion with the user that the label-based solution would be adequate.

**Comment by jameshbarton** [comment]
Related Zendesk ticket: https://solo-io.zendesk.com/agent/tickets/456

**Comment by bewebi** [comment]
This is resolved by solo-io/dev-portal#2120
