### ISSUE TITLE
Portal Group should be mappable to multiple OIDC groups

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo-portal-issues#146]
**Is your feature request related to a problem? Please describe.**
A Portal user needs to map a Portal `Group` to multiple OIDC groups. The API interface is described [here](https://docs.solo.io/gloo-portal/latest/reference/api/group/#groupspec-oidcgroup). It needs to be expanded to support either regex expressions for groupName(s) and/or a list of names / regex expressions.

**Describe the solution you'd like**
Portal Groups should be mappable to multiple OIDC groups.

**Additional context**
Adding this feature may make #145 moot to some extent.

**Comment by jameshbarton** [comment]
Related Zendesk ticket: https://solo-io.zendesk.com/agent/tickets/463

**Comment by jenshu** [comment]
this has been implemented and will be available in Gloo Portal v1.2.0-beta6
