### ISSUE TITLE
Portal should support a "default" group for users with no group claim in JWT

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo-portal-issues#147]
**Is your feature request related to a problem? Please describe.**
A Portal user needs to provide a limited level of default privileges for authenticated users who are not members of any group with Portal access privileges. This is currently impossible.

**Describe the solution you'd like**
Support a "default" or "fallback" group specification whose privileges will be assigned to authenticated users who are not members of any group with Portal access privileges.

**Comment by jameshbarton** [comment]
Related Zendesk ticket: https://solo-io.zendesk.com/agent/tickets/465

**Comment by marcogschmidt** [comment]
This has been implemented and will be available in Gloo Portal `v1.2.0-beta6`.
