### ISSUE TITLE
Portal becomes unavailable when invalid APIProduct configuration is applied

### ISSUE THREAD

**Issue by kcbabo** [solo-io/gloo-portal-issues#153]
**Describe the bug**

**To Reproduce**
1. Update an API Product with incorrect configuration. For instance, set an incorrect operation id (e.g. `headers-incorrect`) for the referenced API Doc.

After that update, you will observer:
1. The APIProduct status transitions to invalid.
2. The Environment status transitions to invalid.
3. The portal CRD status shows Processing.
4. The portal is now not accessible to end users.

**Expected behavior**
Ideal case: implement a validation webhook that validates configuration on apply and rejects invalid configuration. This is likely wrapped up in a much larger epic to provide syntactic and semantic validation for Portal CRs.
Short term: degrade the portal gracefully if bad API product configuration is applied. The portal should still be available, but may show errors or omit APIs if they are invalid.

**Comment by kcbabo** [comment]
https://solo-io.zendesk.com/agent/tickets/482

**Comment by jameshbarton** [comment]
Similar to #152

**Comment by spunuru** [comment]
This issue can also be reproduced by adding a non-existing usagePlan (usagePlan that is defined in Environment CRD) to APIProduct CRD.

**Comment by bewebi** [comment]
This bug has been resolved and is released in v1.2.0-beta7
Environments and Portals will now omit invalid API Products without failing
