### ISSUE TITLE
Portal UI should offer configurable inactive session timeouts

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo-portal-issues#164]
Is your feature request related to a problem? Please describe.
I left a portal instance running in the background for a few days. When I came back, the session was still active. Many enterprise customers will see this as a security risk.

Describe the solution you'd like
The Portal API should support users specifying a timeout setting for inactive sessions. There should also be a default value that doesn't result in indefinitely active sessions.

Brought over from solo-io/dev-portal#1170

**Comment by bewebi** [comment]
This has merged and will release in Gloo Portal v1.4.0-beta4, v1.3.3, and v1.2.23
