### ISSUE TITLE
Version upgrade causes 404s on certain APIProducts

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo-portal-issues#175]
**Describe the bug**
A Portal version upgrade caused 404s with certain APIProducts.

This is the error message:
```
cannot construct versioned field: open static/apidocs/bemsd-athena-sat.service-esignature-service/open_api_schema:
    no such file or directory
```

This may be due to a race condition in the reconciliation process that isn't properly handled.

The workaround was to edit the Environments that contained the failing APIProducts. This forced a reconciliation that fixed the APIProducts.

**To Reproduce**
1. Upgrade Edge Enterprise from 1.11.2 to 1.11.16
2. Upgrade Portal from 1.2.2 to 1.2.5
3. Full process described [here](https://solo-io-corp.slack.com/archives/C02KUC45C13/p1654811420593349).

**Expected behavior**
APIProducts should continue working after version upgrades.

**Additional context**
- Internal Slack [thread](https://solo-io-corp.slack.com/archives/C02KUC45C13/p1654870815525479).
- Related [Zendesk ticket](https://solo-io.zendesk.com/agent/tickets/769).

**Comment by bewebi** [comment]
Traced this to the PR that resolved solo-io/dev-portal#2182, released in 1.2.5
