### ISSUE TITLE
Custom logo not displaying in the password change popup

### ISSUE THREAD

**Issue by day0ops** [solo-io/gloo-portal-issues#178]
**Describe the bug**
Custom logo not rendered correctly in the password change popup. It's still showing the default logo.

<img width="474" alt="Screenshot 2022-07-08 at 1 00 56 AM" src="https://user-images.githubusercontent.com/2648624/177892133-e78f7e7a-cb92-475c-804c-2a1c6014fdab.png">

**To Reproduce**
1. Using basic portal authentication (injecting `User` & `Group`)

**Expected behavior**
Expecting to be able to change the logo to the 

**Additional context**
- Gloo Portal version - `1.2.5`
- Kubernetes version - `1.22`
- Gateway technology and version (e.g. Gloo Edge Enterprise v1.5.11, Istio 1.7) - `GEE 1.11.16`

**Comment by bewebi** [comment]
A fix has been merged in 1.3, 1.2, and 1.1 and will be released in the next release for those versions
