### ISSUE TITLE
Expose a new endpoint to download the stitched openAPI spec for an APIproduct

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo-portal-issues#185]
Expose a new endpoint to download the stitched openAPI spec for an APIproduct.

Phase 2 of https://github.com/solo-io/gloo-portal-issues/issues/87

**Comment by bewebi** [comment]
This is already possible by making a request to `/apiproducts/<namespace>.<product-name>/<version>/open_api_schema`

For our Hello World example this would be `/apiproducts/default.petstore-product/v1/open_api_schema`

Therefore I believe there is no work to be done from a technical standpoint 
Please reopen the issue if additional documentation should be added and/or this endpoint is not a viable solution for whatever reason
