### ISSUE TITLE
Not showing creation timestamp of APIkey and UsagePlan Info details in the Portal UI

### ISSUE THREAD

**Issue by sailinnthu** [solo-io/gloo-portal-issues#191]
**Describe the bug**

<img width="1576" alt="Screenshot 2022-11-28 at 9 33 01 PM" src="https://user-images.githubusercontent.com/11147428/204291669-2f695632-a68a-4d62-a85a-8f34b6a01152.png">

**Expected behavior**
Users able to see the creationtimestamp of when APIkey was created and UsagePlan Info details.

**Additional context**
- Gloo Portal version gloo-portal-1.3.0-beta10

**Comment by bewebi** [comment]
A fix is released as of v1.3.0-beta23
Due to an issue with the release of that version, the first available image with the fix is v1.3.0-beta24
