### ISSUE TITLE
UI Accessibility - Aria tags, full support

### ISSUE THREAD

**Issue by Worfle** [solo-io/gloo-portal-issues#200]
From #199 and #196 

This issue does an exhaustive search of everywhere in the app that we *should* be using aria tags, such as menus/submenus dropdowns or popout/overs.

**Comment by Sodman** [comment]
Hey @Worfle  I see this is in done and the linked PR is merged, are we good to close this out?

**Comment by Worfle** [comment]
Yes, I just had thought it would close out automatically when it went to done. Sorry!
