### ISSUE TITLE
Route to static upstreams 

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo-portal-issues#32]
Today we can route only to Kube upstreams, a lot of users need to route to a static upstream outside of the cluster.

**Comment by casey-robertson** [comment]
Is this on the roadmap?  Any eta ?

**Comment by marcogschmidt** [comment]
@casey-robertson Sorry for the late reply. We are planning to release this at the latest with out Q2 release, but the feature will most likely be available earlier than that.

**Comment by marcogschmidt** [comment]
@asayah @casey-robertson This change has been implemented and will be included in Gloo Portal v1.0.0, which will be released this week.
