### ISSUE TITLE
Portal fails to identify gloo-ee image with port in image spec

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo-portal-issues#35]
**Describe the bug**
Portal fails to detect a gloo-ee image in its cluster when the image spec contains an extra colon (i.e. custom port specification) in the gloo deployment's `spec.containers.env.image` field.  The parser incorrectly assumes there will only be a single colon in the image spec and fails if the image name is something like:

```
my.registry:1234/solo-io/gloo-ee:1.6.0
```

**Comment by arianaw66** [comment]
Closed via https://github.com/solo-io/dev-portal/pull/1321
