### ISSUE TITLE
Portal must allow config to specify non-standard OIDC group scopes

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo-portal-issues#37]
**Describe the bug**
Some portal users store lists of user groups in non-standard scopes in their OIDC provider.  This can break Portal's ability to fetch lists of valid APIs for a given User.  Portal must allow users to configure non-standard scopes for retrieval by Portal.

**Additional context**
- Gloo Portal version 0.6.0

**Comment by marcogschmidt** [comment]
Has been fixed and will be release with `0.6.1`. Will close once the release is out.

**Comment by arianaw66** [comment]
Was released in 0.7.0.
