### ISSUE TITLE
Portal must handle group scopes in common formats like arrays of strings

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo-portal-issues#38]
**Describe the bug**
A Portal user's OIDC provider presents its `groups` scope for an individual user as an array of strings.  Portal today only supports parsing of space-separated values within a single string. 

**Expected behavior**
Support for common grouping structures like arrays of strings should be configurable in addition to the default CSV within a single string.

**Additional context**
- Gloo Portal version 0.6.0

**Comment by marcogschmidt** [comment]
Has been fixed via https://github.com/solo-io/dev-portal/pull/1327 and will be released with `0.6.1`. Will close once the release is out.
