### ISSUE TITLE
Support Environment and APIProduct references by selector / regex

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo-portal-issues#48]
**Is your feature request related to a problem? Please describe.**
A user wants to have a central platform team manage `Portals` and `Environments` but delegate management of `APIDocs` and `APIProducts` to dev teams. This is complicated by the fact that `Environment` requires an explicit list of `APIProducts`. In this management scheme, the platform team would need to update its managed `Environments` anytime a dev team adds or deletes an APIProduct in its portfolio.

Another manifestation of this is that the User CRD in Portal requires an explicit list of `Environments` for an `APIProduct`. Some users have expressed that they would like to use regex or perhaps selectors to choose multiple environments for an `APIProduct`. See the [Access Level API reference](https://docs.solo.io/gloo-portal/latest/reference/api/access_level/) for details.

**Describe the solution you'd like**
Allow all references across the platform/dev team "boundary" to be made by selectors or regexes rather than requiring explicit lists of objects.  For example,`Environments` can refer to `APIProducts` by selector in addition to an explicit list, similar to what Gloo Edge does today with [`VirtualServices` delegating to `RouteTables`](https://docs.solo.io/gloo-edge/latest/guides/traffic_management/destination_types/delegation/#delegation-via-route-table-selector).

**Additional context**
This ticket replaces #33 and #36.

**Comment by marcogschmidt** [comment]
This change has been implemented and will be released as part of the Gloo Portal `v1.0.0` release, which is planned for this week.
