### ISSUE TITLE
Add Schema to Gloo Portal CRDs

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo-portal-issues#49]
**Is your feature request related to a problem? Please describe.**
Some Portal users want to validate their yaml using [kubeeval](https://kubeval.instrumenta.dev/).  They need schema attached to the Portal CRDs to support this.

**Describe the solution you'd like**
Schema are published with Gloo Portal CRDs.

**Comment by marcogschmidt** [comment]
We will tackle this once the schema generation has been implemented for Gloo Edge.

**Comment by jenshu** [comment]
this has been merged and will be available in the next portal release.
a follow-up issue #168 has been filed to handle nested RouteOptions
