### ISSUE TITLE
Portal OIDC Connect fails to find groupName in groups claim if it's not first in the list

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo-portal-issues#50]
**Describe the bug**
Portal OIDC Connect fails to find `groupName` in groups claim if it's not first in the list.  This causes authorization of a user that is in the expected group to fail.  The error indicates that the name of the first group in the list does not match the configured OIDC `groupName`.  And while that is true, Portal should look at the other elements of the list as well.

**To Reproduce**
1. Configure a basic portal with OIDC Connect and an `oidcGroup:groupName:` of `SomeGroup`.
2. Configure IdP provider to return a `groups` claim with multiple groups, where `SomeGroup` is not first in the list.
3. Connect to Portal and attempt OIDC login.  See the error that the name of the first group in the list does not match the configured OIDC `groupName`.

**Expected behavior**
User login should succeed even if the configured `groupName` isn't first in the `groups` claims list.

**Workaround**
From the IdP side, restrict which group names are returned in the `groups` claim.  This workaround is effective for Okta, at least.

**Additional context**
- Gloo Portal version 0.7.0

**Comment by marcogschmidt** [comment]
The relevant code is [here](https://github.com/solo-io/dev-portal/blob/362527f9bf09b428268330308ec9ceb1059db380/pkg/web/server/portalhttp/oidc/internal/oidc_authenticator.go#L89). We should probably error only if none of the groups in the token exist, otherwise just log a warning at "debug" level.

**Comment by arianaw66** [comment]
A fix for this should be released in v0.7.1.
