### ISSUE TITLE
Adding an API to an OIDC Group fails in Portal Dashboard

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo-portal-issues#51]
**Describe the bug**
Adding an API to an OIDC Group fails in Portal Dashboard

**To Reproduce**
1. Setup a basic Portal with an OIDC group integrated from an IdP (Okta, in my case).
2. Use the Portal dashboard to try to add API access to the OIDC group.
3. See error as shown in this [video](https://drive.google.com/file/d/1MkGerMDh_i1H67tfNIdH0FNwY69viuVk/view?usp=sharing).

**Expected behavior**
The OIDC group should be able to add API access with no errors.

**Additional context**
- Gloo Portal version 0.7.0
- Okta IdP to host OIDC user group

**Comment by ascampos** [comment]
this is the same issue as https://github.com/solo-io/dev-portal/issues/1421 which has been fixed by https://github.com/solo-io/dev-portal/pull/1416

**Comment by marcogschmidt** [comment]
Fix will be released with `0.7.2`.
