### ISSUE TITLE
Logging out of Portal web interface does not refresh the logged in user name

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo-portal-issues#52]
**Describe the bug**
Logging out of Portal web interface does not refresh the logged in user name.

**To Reproduce**
1. Create a basic portal with at least one authorized user (in my case, an OIDC user, but I doubt that matters).
2. Login to the portal.  See the username displayed as expected.
3. Logout of the portal.  See that the username is still displayed.  A browser refresh is required to clear the username and return to the blue "Log In" button.

**Expected behavior**
Logging out of the portal should immediately return to the blue "Log In" button.

**Additional context**
- Gloo Portal version 0.7.0

**Comment by marcogschmidt** [comment]
HAs been fixed and will be released with 0.7.2.
