### ISSUE TITLE
Portal auth with OIDC - "securecookie: the value is too long"

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo-portal-issues#56]
When using OIDC to authenticate on a Portal,
If the returned `id_token` or `access_token` is too large,
Then our session management lib throws the following error:
```json
{
  "message": "securecookie: the value is too long"
}
```
Could be related to the Gorilla Session lib: https://github.com/auth0-samples/auth0-golang-web-app/issues/4

More details in our task planning tool.

**Expected behavior**
Being able to handle large session data

**Additional context**
- Gloo Portal version 0.7.1
- Gloo Edge

**Comment by marcogschmidt** [comment]
This problem has been fixed in Gloo Portal 0.7.6.
