### ISSUE TITLE
Portal OIDC authN - read user info to fallback to the UserInfo endpoint

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo-portal-issues#60]
In the authentication workflow on the portal and giving the user a group,
If the `groups` claim (or the claim name defined in the [API](https://docs.solo.io/gloo-portal/latest/reference/api/portal/#devportal.solo.io.PortalSpec.OidcAuth)) is missing from the returned `id_token`, then call the `userinfo_endpoint` as a fallback

Sometimes the information returned in the `id_token` is not enough. More claims are available through the UserInfo endpoint.

**Comment by bewebi** [comment]
With solo-io/dev-portal#1724 we will check `UserInfo` iff the groups claim is not present in the OIDC `id_token`

**Comment by marcogschmidt** [comment]
This fix has been released with Gloo Portal `v1.1.0-beta2`.
