### ISSUE TITLE
Error when creating a Route using the admin web UI

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo-portal-issues#65]
**Describe the bug**
When I create a Route, using the web UI:

![image](https://user-images.githubusercontent.com/9626829/121872319-69e3cf00-cd05-11eb-95de-659f1b44fbe8.png)

![image](https://user-images.githubusercontent.com/9626829/121872330-6bad9280-cd05-11eb-9661-410b413a947f.png)

![image](https://user-images.githubusercontent.com/9626829/121872334-6cdebf80-cd05-11eb-9625-988cd7b7c8cc.png)

The Route is created successfully though if I use `kubectl`. But it still not listed in the Route page, in the web UI

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Portal version 0.7.5
- Kubernetes version KinD 1.21
- Gateway technology and version (e.g. Gloo Edge Enterprise v1.5.11, Istio 1.7) Gloo Edge 1.8 beta

**Comment by bcollard** [comment]
When I refresh the Routes page, after creating 1 Route via the web UI, and another one via a CR:

![image](https://user-images.githubusercontent.com/9626829/121892987-bc30ea00-cd1d-11eb-9e11-472cfcd90abe.png)

![image](https://user-images.githubusercontent.com/9626829/121893020-c7841580-cd1d-11eb-8a7c-4d270c20963e.png)

**Comment by ascampos** [comment]
this issue has been resolved
