### ISSUE TITLE
The UI display a wrong number of APIs for a Portal

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo-portal-issues#7]
A simple way to reproduce the issue is to create a portal without any API.
The UI will display that there's 1 API instead of 0.

Gloo Portal version: 0.4.14

**Comment by djannot** [comment]
![portal-api](https://user-images.githubusercontent.com/3184742/100539036-a8b3ab00-3233-11eb-972c-77593a81d266.png)
![portal](https://user-images.githubusercontent.com/3184742/100539039-a9e4d800-3233-11eb-8022-b8f54f18eff9.png)

**Comment by arianaw66** [comment]
> A simple way to reproduce the issue is to create a portal without any API.
The UI will display that there's 1 API instead of 0.

I see it displaying 0 APIs in that case, but I also see it displaying 0 APIs once I add one. I wonder if it's related to https://github.com/solo-io/dev-portal/issues/1044.

**Comment by arianaw66** [comment]
I think this may be resolved already, and it's hard to test with https://github.com/solo-io/dev-portal/issues/1044 still broken.
Going to wrap it into that issue.
