### ISSUE TITLE
Creating or Editing User in admin dashboard fails

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo-portal-issues#73]
**Describe the bug**
Creating or Editing a User in the admin dashboard fails with this error: "There was an error with the Gloo Portal section"

**To Reproduce**
1. Bring up admin dashboard with no Users or Groups created.
2. Navigate to Access Control
3. Hit "Create a User" 
4. Observe this error.

<img width="1100" alt="Screen Shot 2021-07-06 at 2 10 23 PM" src="https://user-images.githubusercontent.com/52334260/124647415-ee88bf80-de63-11eb-9168-1cb25ba599d5.png">

**Expected behavior**
Dialog is presented to create user.

**Additional context**
- Gloo Portal version 1.0.0
- Gloo Edge Enterprise v1.8.0

**Comment by arianaw66** [comment]
@ascampos
Am I correct that this is a duplicate of https://github.com/solo-io/dev-portal/issues/1725 and should be closed by the https://github.com/solo-io/dev-portal/pull/1726?

**Comment by jameshbarton** [comment]
Closing this - dup of solo-io/dev-portal#1725
