### ISSUE TITLE
Enable Latency for the observability section

### ISSUE THREAD

**Issue by antonioberben** [solo-io/gloo-portal-issues#83]
In the Dev Portal, at the observability section, in the Beta version there was a dropdown offering to show the Latency.

It was on grey (disabled).

It would be interesting to have enabled to display the latency.

Thank you

**Comment by chrisgaun** [comment]
This is Gloo Mesh issue. Can you refile there. Thanks @antonioberben

**Comment by antonioberben** [comment]
Moved to correct repo: https://github.com/solo-io/gloo-mesh/issues/1753
