### ISSUE TITLE
the Route creation wizard fails to validate the form

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo-portal-issues#86]
**Describe the bug**
When I create a new Route, I cannot validate the form in the popin with the Create Route button. Nothing happens after clicking it.

![image](https://user-images.githubusercontent.com/9626829/127026324-7db89f1c-9459-424c-b9da-f7cf9d0311a3.png)

![image](https://user-images.githubusercontent.com/9626829/127026326-20fe9eb9-f235-42f4-8473-a7df972432a0.png)

![image](https://user-images.githubusercontent.com/9626829/127026330-f2375699-7ea3-461b-87a8-75ec907fbdb7.png)

Another example with some weights on destinations, same issue:

![image](https://user-images.githubusercontent.com/9626829/127026333-40f17776-d888-4fac-83e0-f65a7ef82f0b.png)

![image](https://user-images.githubusercontent.com/9626829/127026332-5d9046e7-6ce3-4e4d-bda7-79e66cd59720.png)

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Portal version 1.0.1
- Gateway technology and version (e.g. Gloo Edge Enterprise v1.5.11, Istio 1.7) 1.8

**Comment by marcogschmidt** [comment]
This has been fixed and will be released with Gloo Portal `v1.0.2` and `v1.1.0-beta3`.
