### ISSUE TITLE
`Define a Route` button in APIProducts admin UI generates error

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo-portal-issues#89]
**Describe the bug**
The `Define a Route` button in APIProducts admin UI generates error message:
"There was an error trying to get details for petstore."

**To Reproduce**
1. Visit demo portal: http://portal-admin.demo.solo.io/api-products/gloo-system/petstore

![Screen Shot 2021-08-03 at 4 08 03 PM](https://user-images.githubusercontent.com/52334260/128086890-6abdb5a3-dd0b-4ab5-91a3-c0e8bdec522a.png)

2. Click a `Define a Route` button.
3. See error

![Screen Shot 2021-08-03 at 4 13 31 PM](https://user-images.githubusercontent.com/52334260/128087092-d289140b-defb-49c6-9f4f-c4e4b66cbfa4.png)

**Expected behavior**
This should allow us to define a route without error.

**Additional context**
- Gloo Portal version 1.1.0-beta2 (in demo Portal instance)
- Gloo Edge Enterprise version 1.8.0

**Comment by chrisgaun** [comment]
Dedupe

**Comment by chrisgaun** [comment]
@ascampos @arianaw66 this is issue that came up with user. We might have already identified this as part of the bug hunt.

**Comment by arianaw66** [comment]
Yup, first bullet point [here](https://github.com/solo-io/dev-portal/issues/1811)

**Comment by marcogschmidt** [comment]
Fix has merged and will be released with `v1.1.0-beta5`/`v1.0.3`.
