### ISSUE TITLE
API long description not displayed correctly and blocking the button to create a new API doc

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo-portal-issues#9]
I think we should use a scroll overflow when the description is too long.

It should improve the display and also avoid the issue with the button.

Gloo Portal version: 0.4.14

**Comment by djannot** [comment]
[bookinfo-long-description.yaml.zip](https://github.com/solo-io/istio-dev-portal-issues/files/5612002/bookinfo-long-description.yaml.zip)

![portal-long](https://user-images.githubusercontent.com/3184742/100539177-eb29b780-3234-11eb-98d0-3f223b07bb5b.png)

**Comment by jehawley** [comment]
A fix has been committed. It will be released in v0.5.1.
